### ISSUE TITLE
Can i use it in a non ES6 environment ?

### ISSUE THREAD

**Issue by manodupont** [hiddentao/simple-mongo-schema#2]

**Comment by hiddentao** [comment]
Unfortunately not, since it relies on generators. This was a design decision made to allow for asynchronous custom validators.

**Comment by hiddentao** [comment]
Going to rename this to `simple-nosql-schema` and rewrite using Promises so that ES5 environments will also be supported.

**Comment by hiddentao** [comment]
Now available -> https://github.com/hiddentao/simple-nosql-schema
